apiVersion: batch/v1
kind: Job
metadata:
  name: rna-seq-test-read
spec:
  backoffLimit: 0
  completions: 1
  template:
    metadata:
      labels:
        k8s-app: rna-seq-test-read
    spec:
      restartPolicy: Never
      containers:
      - name: rna-seq-test-read
        image: jmlehrer/cell-exploration:latest
        command: ["stdbuf", "-i0", "-o0", "-e0", "bash", "-c"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        args: ["python notebooks/test.py"]
        resources:
          limits:
            memory: 16Gi
            cpu: "8"
          requests:
            memory: 16Gi
            cpu: "8"
        volumeMounts:
        - name: ephemeral
          mountPath: "/data"
      volumes:
      # Ephemeral storage
      - name: ephemeral
        emptyDir: {}