apiVersion: batch/v1
kind: Job
metadata:
  name: rna-seq-annotation
spec:
  backoffLimit: 1
  completions: 1
  template:
    metadata:
      labels:
        k8s-app: rna-seq-annotation
    spec:
      restartPolicy: Never
      containers:
      - name: rna-seq-annotation
        image: jmlehrer/cell-exploration:latest
        command: ["stdbuf", "-i0", "-o0", "-e0", "bash", "-c"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        args: [
          "python src/data/download_data.py -type='labels' && \ 
          python src/data/download_data.py -type='primary' && \
          python src/models/cluster_annotation.py"
        ]
        resources:
          limits:
            memory: 500Gi
            cpu: "32"
          requests:
            memory: 64Gi
            cpu: "8"