apiVersion: batch/v1
kind: Job
metadata:
  name: rna-seq-cluster
spec:
  backoffLimit: 0
  completions: 1
  template:
    metadata:
      labels:
        k8s-app: rna-seq-cluster
    spec:
      restartPolicy: Never
      containers:
      - name: rna-seq-cluster
        image: jmlehrer/cell-exploration:latest
        command: ["stdbuf", "-i0", "-o0", "-e0", "bash", "-c"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        args: ["python src/data/download_data -type='reduced' && python src/models/clustering.py"]
        resources:
          limits:
            memory: 100Gi
            cpu: "24"
          requests:
            memory: 64Gi
            cpu: "8"
        volumeMounts:
        - name: ephemeral
          mountPath: "/data"
      volumes:
      - name: ephemeral
        emptyDir: {}