apiVersion: batch/v1
kind: Job
metadata:
  name: rna-seq-model-weighting-width-${WIDTH}-layers-${LAYERS}-${I}
spec:
  backoffLimit: 5
  completions: 1
  template:
    metadata:
      labels:
        k8s-app: rna-seq-model-5-layer-complexity-weighted
    spec:
      restartPolicy: Never
      containers:
      - name: rna-seq-model-5-layer-complexity-weighted
        image: jmlehrer/cell-exploration:latest
        command: ["stdbuf", "-i0", "-o0", "-e0", "bash", "-c"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        args: [
          "python src/data/download_data.py -type='primary' && \
          python src/data/download_data.py -type='labels' && \
          python src/models/train_neural_network.py \
          --width=${WIDTH} --layers=${LAYERS} \
          --lr=${LR} --momentum=${MOMENTUM} --weight-decay=${WEIGHT_DECAY}"
        ]
        resources:
          limits:
            memory: 100Gi
            cpu: "16"
            nvidia.com/gpu: "1"
          requests:
            memory: 32Gi
            cpu: "12"
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: ephemeral
          mountPath: "/data"
      volumes:
      # Ephemeral storage
      - name: ephemeral
        emptyDir: {}
      tolerations:
        - key: "nautilus.io/chase-ci"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: NotIn
      #           values:
      #             - k8s-gpu-1.ucr.edu                # 9nov: GPU sync failed
      #             - fiona8-2.calit2.uci.edu       # 16nov: Driver error timeout
