apiVersion: batch/v1
kind: Job
metadata:
  name: rna-seq-train-deep-model
spec:
  backoffLimit: 0
  completions: 1
  template:
    metadata:
      labels:
        k8s-app: rna-seq-train-deep-model
    spec:
      restartPolicy: Never
      containers:
      - name: rna-seq-train-deep-model
        image: jmlehrer/cell-exploration:latest
        command: ["stdbuf", "-i0", "-o0", "-e0", "bash", "-c"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        args: [
          "python src/data/download_data.py -type='clean' && \
          python src/data/download_data.py -type='reduced' && \
          python src/models/train_neural_network.py"]
        resources:
          limits:
            memory: 100Gi
            cpu: "16"
          requests:
            memory: 72Gi
            cpu: "16"
        volumeMounts:
        - name: ephemeral
          mountPath: "/data"
      volumes:
      # Ephemeral storage
      - name: ephemeral
        emptyDir: {}