apiVersion: batch/v1
kind: Job
metadata:
  name: rna-seq-reduction-${N}-neighbors-${COMP}-components
spec:
  backoffLimit: 1
  completions: 1
  template:
    metadata:
      labels:
        k8s-app: rna-seq-reduction-${N}-neighbors-${COMP}-components
    spec:
      restartPolicy: Never
      containers:
      - name: rna-seq-reduction-${N}-neighbors-${COMP}-components
        image: jmlehrer/cell-exploration:latest
        command: ["stdbuf", "-i0", "-o0", "-e0", "bash", "-c"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        args: ["python src/data/download_data.py -type=interim && python src/models/reduction.py -neighbors=${N} -components=${COMP}"]
        resources:
          limits:
            memory: 250Gi
            cpu: "32"
          requests:
            memory: 72Gi
            cpu: "16"
        volumeMounts:
        - name: ephemeral
          mountPath: "/data"
      volumes:
      - name: ephemeral
        emptyDir: {}