apiVersion: batch/v1
kind: Job
metadata:
  name: rna-seq-reduction-${N}-neighbors-${COMP}-components-${FILE}
spec:
  backoffLimit: 0
  completions: 1
  template:
    metadata:
      labels:
        k8s-app: rna-seq-reduction-${N}-neighbors-${COMP}-components-${FILE}
    spec:
      restartPolicy: Never
      containers:
      - name: rna-seq-reduction-${N}-neighbors-${COMP}-components-${FILE}
        image: jmlehrer/cell-exploration:latest
        command: ["stdbuf", "-i0", "-o0", "-e0", "bash", "-c"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        args: [
          "python src/data/download_data.py -type='clean' && \
          python src/models/umap_calc.py -neighbors=${N} -components=${COMP} -file=${FILE}"
        ]
        resources:
          limits:
            memory: 500Gi
            cpu: "32"
          requests:
            memory: 250Gi
            cpu: "24"
        volumeMounts:
        - name: ephemeral
          mountPath: "/data"
      volumes:
      - name: ephemeral
        emptyDir: {}